version: 0.1.{build}

environment:
  matrix:
  - example: Crypto-x86
    name: win32
    qt: mingw53_32
  - example: Crypto-x64
    name: win64
    qt: msvc2015_64

install:
  - set QTDIR=C:\Qt\5.10.1\%qt%
  - set PATH=%PATH%;%QTDIR%\bin;C:\MinGW\bin

build_script:
  - qmake Cryptor.pro
  - mingw32-make
