before_install:
- sudo add-apt-repository -y ppa:beineri/opt-qt593-trusty
- sudo apt-get -qq update

install:
- sudo apt-get -qy install qt59-meta-minimal
- sudo apt-get -qy install g++
- sudo apt-get -qy install qt5-qmake qtbase5-dev

before_script:
- export PATH=/opt/qt59/bin:$PATH
- export QTDIR=/opt/qt59

script:
 - qmake --version
 - mkdir build
 - cd build
 - qmake ..
 - make
